version: '3'

services:
  app:
    build: .
    command: npm run dev
    ports:
      - '8000:8000'
    volumes:
      - .:/home/node/app

  database:
    container_name: 'database'
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
