version: '3'

services:
  app:
    build: .
    command: npm run dev
    ports:
      - '8000:8000'
    volumes:
      - .:/home/node/app

  database:
    container_name: 'database'
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp --wait-timeout=28800 --max-connections=1000 --max_allowed_packet=256M
